language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - pypy

before_install: pip install --use-mirrors nose

script:
  - cd py-appscript/trunk
  - python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION > "3" ]]; then nosetests appscript_3x/test/*.py; else nosetests appscript_2x/test/*.py; fi

